services:
  backend:
    build:
      context: ./acko-backend
      dockerfile: Dockerfile
    container_name: node-backend
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - MONGO_HOST=metadata-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=acko-metadata
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=acko1
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=acko
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=acko0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - REDIS_BROKER_HOST=redis-broker
      - REDIS_BROKER_PORT=6379
      - REDIS_BROKER_PASSWORD=redis-broker
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mysql
      - postgres
      - metadata-db
      - redis
      - redis-broker
    # volumes:
    #   - ./acko-backend:/app
    restart: always
    hostname: backend
    networks:
      - acko-network

  frontend:
    build:
      context: ./acko-frontend
      dockerfile: Dockerfile
    container_name: node-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_SOURCE_TYPES=mysql,postgresql
      - REACT_APP_DESTINATION_TYPES=mysql,postgresql,csv
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    # volumes:
    #   - ./acko-frontend:/app
    restart: always
    networks:
      - acko-network

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acko0
      MYSQL_USER: acko
      MYSQL_PASSWORD: root
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/sql/mysql:/docker-entrypoint-initdb.d
    networks:
      - acko-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acko1
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./init/sql/postgres:/docker-entrypoint-initdb.d
    networks:
      - acko-network

  metadata-db:
    image: mongo
    container_name: metadata-db
    ports:
      - '27017:27017'
    networks:
      - acko-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - redis_data:/data
    networks:
      - acko-network

  redis-broker:
    image: redis:6.2-alpine
    container_name: redis-broker
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis-broker
    volumes:
      - redis_broker_data:/data
    networks:
      - acko-network

volumes:
  mysql_data:
  postgres_data:
  redis_data:
  redis_broker_data:

networks:
  acko-network:
    driver: bridge
